//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34209
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class General {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal General() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.General", typeof(General).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to About Us.
        /// </summary>
        public static string AboutUs {
            get {
                return ResourceManager.GetString("AboutUs", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your Account  Is Locked !.
        /// </summary>
        public static string AccountLock {
            get {
                return ResourceManager.GetString("AccountLock", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Actions.
        /// </summary>
        public static string Actions {
            get {
                return ResourceManager.GetString("Actions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Activate.
        /// </summary>
        public static string Activate {
            get {
                return ResourceManager.GetString("Activate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string Active {
            get {
                return ResourceManager.GetString("Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Active.
        /// </summary>
        public static string ActiveState {
            get {
                return ResourceManager.GetString("ActiveState", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add.
        /// </summary>
        public static string Add {
            get {
                return ResourceManager.GetString("Add", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add All.
        /// </summary>
        public static string AddAll {
            get {
                return ResourceManager.GetString("AddAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Basket.
        /// </summary>
        public static string AddBasket {
            get {
                return ResourceManager.GetString("AddBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Choosen.
        /// </summary>
        public static string AddChoosen {
            get {
                return ResourceManager.GetString("AddChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Category.
        /// </summary>
        public static string AddNewCategory {
            get {
                return ResourceManager.GetString("AddNewCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add News.
        /// </summary>
        public static string AddNews {
            get {
                return ResourceManager.GetString("AddNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AddNewsSubCategory.
        /// </summary>
        public static string AddNewsSubCategory {
            get {
                return ResourceManager.GetString("AddNewsSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Price.
        /// </summary>
        public static string AddPrice {
            get {
                return ResourceManager.GetString("AddPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Trader User.
        /// </summary>
        public static string AddTraderUsers {
            get {
                return ResourceManager.GetString("AddTraderUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Admin Questions.
        /// </summary>
        public static string AdminQuestions {
            get {
                return ResourceManager.GetString("AdminQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Advanced Search.
        /// </summary>
        public static string AdvancedSearch {
            get {
                return ResourceManager.GetString("AdvancedSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to All.
        /// </summary>
        public static string All {
            get {
                return ResourceManager.GetString("All", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Allow others to view my profile data.
        /// </summary>
        public static string AllowGeneralProfile {
            get {
                return ResourceManager.GetString("AllowGeneralProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to AM.
        /// </summary>
        public static string am {
            get {
                return ResourceManager.GetString("am", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Answer.
        /// </summary>
        public static string answer {
            get {
                return ResourceManager.GetString("answer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ask.
        /// </summary>
        public static string Ask {
            get {
                return ResourceManager.GetString("Ask", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Assign Favorites.
        /// </summary>
        public static string AssignFavLink {
            get {
                return ResourceManager.GetString("AssignFavLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Available.
        /// </summary>
        public static string Available {
            get {
                return ResourceManager.GetString("Available", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Close.
        /// </summary>
        public static string AverageClose {
            get {
                return ResourceManager.GetString("AverageClose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Average Price.
        /// </summary>
        public static string AveragePrice {
            get {
                return ResourceManager.GetString("AveragePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to Basket.
        /// </summary>
        public static string BackToBasket {
            get {
                return ResourceManager.GetString("BackToBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackToPricePage.
        /// </summary>
        public static string BackToPricePage {
            get {
                return ResourceManager.GetString("BackToPricePage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to BackToTraders.
        /// </summary>
        public static string BackToTraders {
            get {
                return ResourceManager.GetString("BackToTraders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bar.
        /// </summary>
        public static string Bar {
            get {
                return ResourceManager.GetString("Bar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traders Basket.
        /// </summary>
        public static string Basket {
            get {
                return ResourceManager.GetString("Basket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Buy.
        /// </summary>
        public static string BasketBuy {
            get {
                return ResourceManager.GetString("BasketBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Name.
        /// </summary>
        public static string BasketName {
            get {
                return ResourceManager.GetString("BasketName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket prices history.
        /// </summary>
        public static string basketPriceHistory {
            get {
                return ResourceManager.GetString("basketPriceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Prices.
        /// </summary>
        public static string BasketPrices {
            get {
                return ResourceManager.GetString("BasketPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Baskets.
        /// </summary>
        public static string Baskets {
            get {
                return ResourceManager.GetString("Baskets", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Basket Sell.
        /// </summary>
        public static string BasketSell {
            get {
                return ResourceManager.GetString("BasketSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Basket.
        /// </summary>
        public static string BasketUpdate {
            get {
                return ResourceManager.GetString("BasketUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bid.
        /// </summary>
        public static string Bid {
            get {
                return ResourceManager.GetString("Bid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy.
        /// </summary>
        public static string Buy {
            get {
                return ResourceManager.GetString("Buy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to buyMax.
        /// </summary>
        public static string buyMax {
            get {
                return ResourceManager.GetString("buyMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy Price.
        /// </summary>
        public static string BuyPrice {
            get {
                return ResourceManager.GetString("BuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buy/Sell.
        /// </summary>
        public static string BuySell {
            get {
                return ResourceManager.GetString("BuySell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cancel search.
        /// </summary>
        public static string CancelSearch {
            get {
                return ResourceManager.GetString("CancelSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to verification Code.
        /// </summary>
        public static string Captcha {
            get {
                return ResourceManager.GetString("Captcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carat 10.
        /// </summary>
        public static string Carat10 {
            get {
                return ResourceManager.GetString("Carat10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carat 14.
        /// </summary>
        public static string Carat14 {
            get {
                return ResourceManager.GetString("Carat14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carat 18.
        /// </summary>
        public static string Carat18 {
            get {
                return ResourceManager.GetString("Carat18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carat 21.
        /// </summary>
        public static string Carat21 {
            get {
                return ResourceManager.GetString("Carat21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to carat 22.
        /// </summary>
        public static string carat22 {
            get {
                return ResourceManager.GetString("carat22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carat 24.
        /// </summary>
        public static string Carat24 {
            get {
                return ResourceManager.GetString("Carat24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب الفئة.
        /// </summary>
        public static string CategoryOrder {
            get {
                return ResourceManager.GetString("CategoryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Change Language.
        /// </summary>
        public static string ChangeLanguage {
            get {
                return ResourceManager.GetString("ChangeLanguage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cahnge password.
        /// </summary>
        public static string ChangePassword {
            get {
                return ResourceManager.GetString("ChangePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chat Room.
        /// </summary>
        public static string ChatRoom {
            get {
                return ResourceManager.GetString("ChatRoom", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and confirm your email address.
        /// </summary>
        public static string CheckMail {
            get {
                return ResourceManager.GetString("CheckMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check your email and confirm your email address.
        /// </summary>
        public static string CheckMailPassword {
            get {
                return ResourceManager.GetString("CheckMailPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Category.
        /// </summary>
        public static string ChooseCategory {
            get {
                return ResourceManager.GetString("ChooseCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Date.
        /// </summary>
        public static string ChooseDate {
            get {
                return ResourceManager.GetString("ChooseDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Choose Group.
        /// </summary>
        public static string ChooseGroup {
            get {
                return ResourceManager.GetString("ChooseGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to choose Main Category.
        /// </summary>
        public static string chooseMainCategory {
            get {
                return ResourceManager.GetString("chooseMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ChooseT rader.
        /// </summary>
        public static string ChooseTrader {
            get {
                return ResourceManager.GetString("ChooseTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chossen.
        /// </summary>
        public static string Chossen {
            get {
                return ResourceManager.GetString("Chossen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to City.
        /// </summary>
        public static string City {
            get {
                return ResourceManager.GetString("City", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Close.
        /// </summary>
        public static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Comment.
        /// </summary>
        public static string Comment {
            get {
                return ResourceManager.GetString("Comment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Common Questions.
        /// </summary>
        public static string ComonQuestions {
            get {
                return ResourceManager.GetString("ComonQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ComparasonTraders.
        /// </summary>
        public static string ComparasonTraders {
            get {
                return ResourceManager.GetString("ComparasonTraders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to comparsonChart.
        /// </summary>
        public static string comparsonChart {
            get {
                return ResourceManager.GetString("comparsonChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Mail.
        /// </summary>
        public static string ConfirmMail {
            get {
                return ResourceManager.GetString("ConfirmMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm New Password.
        /// </summary>
        public static string ConfirmNewPassword {
            get {
                return ResourceManager.GetString("ConfirmNewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Confirm Password.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Complete the process of login.
        /// </summary>
        public static string ContinueLogin {
            get {
                return ResourceManager.GetString("ContinueLogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Buy.
        /// </summary>
        public static string CurrentBuy {
            get {
                return ResourceManager.GetString("CurrentBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Sell.
        /// </summary>
        public static string CurrentSell {
            get {
                return ResourceManager.GetString("CurrentSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Current Password.
        /// </summary>
        public static string CurrPassword {
            get {
                return ResourceManager.GetString("CurrPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dashboard.
        /// </summary>
        public static string Dashboard {
            get {
                return ResourceManager.GetString("Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to day month.
        /// </summary>
        public static string daymonth {
            get {
                return ResourceManager.GetString("daymonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to deactive.
        /// </summary>
        public static string deactive {
            get {
                return ResourceManager.GetString("deactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete.
        /// </summary>
        public static string Delete {
            get {
                return ResourceManager.GetString("Delete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete All.
        /// </summary>
        public static string DeleteAll {
            get {
                return ResourceManager.GetString("DeleteAll", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Choosen.
        /// </summary>
        public static string DeleteChoosen {
            get {
                return ResourceManager.GetString("DeleteChoosen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Description.
        /// </summary>
        public static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dollar Price.
        /// </summary>
        public static string DollarPrice1 {
            get {
                return ResourceManager.GetString("DollarPrice1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit.
        /// </summary>
        public static string Edit {
            get {
                return ResourceManager.GetString("Edit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Profile.
        /// </summary>
        public static string EditProfile {
            get {
                return ResourceManager.GetString("EditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit Trader Profile.
        /// </summary>
        public static string EditTraderProfile {
            get {
                return ResourceManager.GetString("EditTraderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Edit User Profile.
        /// </summary>
        public static string EditUserProfile {
            get {
                return ResourceManager.GetString("EditUserProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email.
        /// </summary>
        public static string Email {
            get {
                return ResourceManager.GetString("Email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Enter Captcha.
        /// </summary>
        public static string EnterCaptcha {
            get {
                return ResourceManager.GetString("EnterCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PDF.
        /// </summary>
        public static string ExportTpPDF {
            get {
                return ResourceManager.GetString("ExportTpPDF", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions.
        /// </summary>
        public static string FAQ {
            get {
                return ResourceManager.GetString("FAQ", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorate List.
        /// </summary>
        public static string FavorateList {
            get {
                return ResourceManager.GetString("FavorateList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favourite List Management.
        /// </summary>
        public static string FavouriteListManagement {
            get {
                return ResourceManager.GetString("FavouriteListManagement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to FavPriceListTitle.
        /// </summary>
        public static string FavPriceListTitle {
            get {
                return ResourceManager.GetString("FavPriceListTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Feedback.
        /// </summary>
        public static string Feedback {
            get {
                return ResourceManager.GetString("Feedback", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gold .
        /// </summary>
        public static string FeedbackSubject {
            get {
                return ResourceManager.GetString("FeedbackSubject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Female.
        /// </summary>
        public static string Female {
            get {
                return ResourceManager.GetString("Female", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Filter {
            get {
                return ResourceManager.GetString("Filter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First Name.
        /// </summary>
        public static string FirstName {
            get {
                return ResourceManager.GetString("FirstName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to First privilage.
        /// </summary>
        public static string FirstPrivilage {
            get {
                return ResourceManager.GetString("FirstPrivilage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Forgot Password?.
        /// </summary>
        public static string ForgotPassword {
            get {
                return ResourceManager.GetString("ForgotPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to of.
        /// </summary>
        public static string From {
            get {
                return ResourceManager.GetString("From", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gender.
        /// </summary>
        public static string Gender {
            get {
                return ResourceManager.GetString("Gender", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to General Gold Prices In Egypt.
        /// </summary>
        public static string generalGoldPrices {
            get {
                return ResourceManager.GetString("generalGoldPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Generate Password.
        /// </summary>
        public static string GeneratePassword {
            get {
                return ResourceManager.GetString("GeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global Gold Chart.
        /// </summary>
        public static string GlobalChart {
            get {
                return ResourceManager.GetString("GlobalChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global gold prices.
        /// </summary>
        public static string GlobalGoldPrices {
            get {
                return ResourceManager.GetString("GlobalGoldPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to global market.
        /// </summary>
        public static string globalmarket {
            get {
                return ResourceManager.GetString("globalmarket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Gold latest price.
        /// </summary>
        public static string GoldLatestPrice {
            get {
                return ResourceManager.GetString("GoldLatestPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Global And Local Gold Prices.
        /// </summary>
        public static string GoldNews {
            get {
                return ResourceManager.GetString("GoldNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoldPrice1gm.
        /// </summary>
        public static string GoldPrice1gm {
            get {
                return ResourceManager.GetString("GoldPrice1gm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gold prices month.
        /// </summary>
        public static string goldpricesmonth {
            get {
                return ResourceManager.GetString("goldpricesmonth", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to gold prices week.
        /// </summary>
        public static string goldpricesweek {
            get {
                return ResourceManager.GetString("goldpricesweek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Goldsmiths.
        /// </summary>
        public static string Goldsmiths {
            get {
                return ResourceManager.GetString("Goldsmiths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kilogram of gold calibres 21.
        /// </summary>
        public static string GoldText1 {
            get {
                return ResourceManager.GetString("GoldText1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Half kilogram of gold calibres 18.
        /// </summary>
        public static string GoldText2 {
            get {
                return ResourceManager.GetString("GoldText2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoToFavPriceList.
        /// </summary>
        public static string GoToFavPriceList {
            get {
                return ResourceManager.GetString("GoToFavPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to GoToMainPriceList.
        /// </summary>
        public static string GoToMainPriceList {
            get {
                return ResourceManager.GetString("GoToMainPriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Governorate.
        /// </summary>
        public static string Governorate {
            get {
                return ResourceManager.GetString("Governorate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group.
        /// </summary>
        public static string Group {
            get {
                return ResourceManager.GetString("Group", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hello.
        /// </summary>
        public static string Hello {
            get {
                return ResourceManager.GetString("Hello", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to High.
        /// </summary>
        public static string High {
            get {
                return ResourceManager.GetString("High", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Home.
        /// </summary>
        public static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hours.
        /// </summary>
        public static string Hours {
            get {
                return ResourceManager.GetString("Hours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to InBasket Prices.
        /// </summary>
        public static string InBasketPrices {
            get {
                return ResourceManager.GetString("InBasketPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Isactive/Inactive.
        /// </summary>
        public static string isactive {
            get {
                return ResourceManager.GetString("isactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest.
        /// </summary>
        public static string IsLatest {
            get {
                return ResourceManager.GetString("IsLatest", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Name.
        /// </summary>
        public static string LastName {
            get {
                return ResourceManager.GetString("LastName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Last Update.
        /// </summary>
        public static string LastPriceDate {
            get {
                return ResourceManager.GetString("LastPriceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Egyption pound.
        /// </summary>
        public static string leprice {
            get {
                return ResourceManager.GetString("leprice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Line.
        /// </summary>
        public static string Line {
            get {
                return ResourceManager.GetString("Line", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to List prices throughout the day.
        /// </summary>
        public static string ListPrices {
            get {
                return ResourceManager.GetString("ListPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loacle Gold News.
        /// </summary>
        public static string LoacleGoldNews {
            get {
                return ResourceManager.GetString("LoacleGoldNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Loading ......
        /// </summary>
        public static string Loading {
            get {
                return ResourceManager.GetString("Loading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Login.
        /// </summary>
        public static string Login {
            get {
                return ResourceManager.GetString("Login", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Click here to Log in.
        /// </summary>
        public static string loginLink {
            get {
                return ResourceManager.GetString("loginLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Logout.
        /// </summary>
        public static string Logout {
            get {
                return ResourceManager.GetString("Logout", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Low.
        /// </summary>
        public static string Low {
            get {
                return ResourceManager.GetString("Low", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main User.
        /// </summary>
        public static string MainUser {
            get {
                return ResourceManager.GetString("MainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Male.
        /// </summary>
        public static string Male {
            get {
                return ResourceManager.GetString("Male", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage Favourites.
        /// </summary>
        public static string ManageFav {
            get {
                return ResourceManager.GetString("ManageFav", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manage User.
        /// </summary>
        public static string ManageUsers {
            get {
                return ResourceManager.GetString("ManageUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best BuyPrice.
        /// </summary>
        public static string maxBuyPrice {
            get {
                return ResourceManager.GetString("maxBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Sell price.
        /// </summary>
        public static string maxPrice {
            get {
                return ResourceManager.GetString("maxPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Max Sell.
        /// </summary>
        public static string maxSellPrice {
            get {
                return ResourceManager.GetString("maxSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Min Buy.
        /// </summary>
        public static string minBuyPrice {
            get {
                return ResourceManager.GetString("minBuyPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best Buy price.
        /// </summary>
        public static string minPrice {
            get {
                return ResourceManager.GetString("minPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Best SellPrice.
        /// </summary>
        public static string minSellPrice {
            get {
                return ResourceManager.GetString("minSellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minutes.
        /// </summary>
        public static string Minutes {
            get {
                return ResourceManager.GetString("Minutes", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MngFavList.
        /// </summary>
        public static string MngFavList {
            get {
                return ResourceManager.GetString("MngFavList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Mobile.
        /// </summary>
        public static string Mobile {
            get {
                return ResourceManager.GetString("Mobile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month.
        /// </summary>
        public static string Month {
            get {
                return ResourceManager.GetString("Month", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Month/Week.
        /// </summary>
        public static string MonthWeek {
            get {
                return ResourceManager.GetString("MonthWeek", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name.
        /// </summary>
        public static string Name {
            get {
                return ResourceManager.GetString("Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to New Password.
        /// </summary>
        public static string NewPassword {
            get {
                return ResourceManager.GetString("NewPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Category.
        /// </summary>
        public static string NewsCategory {
            get {
                return ResourceManager.GetString("NewsCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Category.
        /// </summary>
        public static string NewsCategoryText {
            get {
                return ResourceManager.GetString("NewsCategoryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Count.
        /// </summary>
        public static string NewsCount {
            get {
                return ResourceManager.GetString("NewsCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Date.
        /// </summary>
        public static string NewsDate {
            get {
                return ResourceManager.GetString("NewsDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Details.
        /// </summary>
        public static string NewsDetails {
            get {
                return ResourceManager.GetString("NewsDetails", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Back to news list.
        /// </summary>
        public static string NewsList {
            get {
                return ResourceManager.GetString("NewsList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Main Category.
        /// </summary>
        public static string NewsMainCategory {
            get {
                return ResourceManager.GetString("NewsMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can&apos;t add more than two main category..
        /// </summary>
        public static string NewsMainCategoryMaxVal {
            get {
                return ResourceManager.GetString("NewsMainCategoryMaxVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to عنوان الفئه الرئيسيه للاخبار.
        /// </summary>
        public static string NewsMainCategoryName {
            get {
                return ResourceManager.GetString("NewsMainCategoryName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ترتيب الفئه الرئيسيه للاخبار.
        /// </summary>
        public static string NewsMainCategoryOrder {
            get {
                return ResourceManager.GetString("NewsMainCategoryOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Most viewed.
        /// </summary>
        public static string NewsMostViewed {
            get {
                return ResourceManager.GetString("NewsMostViewed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Order.
        /// </summary>
        public static string NewsOrder {
            get {
                return ResourceManager.GetString("NewsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Source.
        /// </summary>
        public static string NewsSource {
            get {
                return ResourceManager.GetString("NewsSource", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News Source URL.
        /// </summary>
        public static string NewsSourceURL {
            get {
                return ResourceManager.GetString("NewsSourceURL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to الفئة الفرعية.
        /// </summary>
        public static string NewsSubCategory {
            get {
                return ResourceManager.GetString("NewsSubCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Summary.
        /// </summary>
        public static string NewsSummary {
            get {
                return ResourceManager.GetString("NewsSummary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Title.
        /// </summary>
        public static string NewsTitle {
            get {
                return ResourceManager.GetString("NewsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update News.
        /// </summary>
        public static string NewsUpdate {
            get {
                return ResourceManager.GetString("NewsUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to News.
        /// </summary>
        public static string NewsUser {
            get {
                return ResourceManager.GetString("NewsUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Next.
        /// </summary>
        public static string Next {
            get {
                return ResourceManager.GetString("Next", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Answers Questions.
        /// </summary>
        public static string NoAnswersQuestions {
            get {
                return ResourceManager.GetString("NoAnswersQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Category Questions.
        /// </summary>
        public static string NoCategoryQuestions {
            get {
                return ResourceManager.GetString("NoCategoryQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Movements 0.
        /// </summary>
        public static string NoOfmovements {
            get {
                return ResourceManager.GetString("NoOfmovements", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Movements {0}.
        /// </summary>
        public static string NoOfmovements1 {
            get {
                return ResourceManager.GetString("NoOfmovements1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Results to preview.
        /// </summary>
        public static string NoResults {
            get {
                return ResourceManager.GetString("NoResults", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Not active.
        /// </summary>
        public static string notactive {
            get {
                return ResourceManager.GetString("notactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to notreplied.
        /// </summary>
        public static string notreplied {
            get {
                return ResourceManager.GetString("notreplied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Number Of Questions.
        /// </summary>
        public static string NumberOfQuestions {
            get {
                return ResourceManager.GetString("NumberOfQuestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Old Password.
        /// </summary>
        public static string OldPassword {
            get {
                return ResourceManager.GetString("OldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open.
        /// </summary>
        public static string Open {
            get {
                return ResourceManager.GetString("Open", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Buy.
        /// </summary>
        public static string OpenBuy {
            get {
                return ResourceManager.GetString("OpenBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Open Sell.
        /// </summary>
        public static string OpenSell {
            get {
                return ResourceManager.GetString("OpenSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to OtherTraders.
        /// </summary>
        public static string OtherTraders {
            get {
                return ResourceManager.GetString("OtherTraders", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Page.
        /// </summary>
        public static string Page {
            get {
                return ResourceManager.GetString("Page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PageSizeChoose.
        /// </summary>
        public static string PageSizeChoose {
            get {
                return ResourceManager.GetString("PageSizeChoose", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password.
        /// </summary>
        public static string Password {
            get {
                return ResourceManager.GetString("Password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed.
        /// </summary>
        public static string PasswordChanged {
            get {
                return ResourceManager.GetString("PasswordChanged", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to period.
        /// </summary>
        public static string period {
            get {
                return ResourceManager.GetString("period", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Periods.
        /// </summary>
        public static string Periods {
            get {
                return ResourceManager.GetString("Periods", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Personal Information.
        /// </summary>
        public static string PersonalInformation {
            get {
                return ResourceManager.GetString("PersonalInformation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to phone.
        /// </summary>
        public static string phone {
            get {
                return ResourceManager.GetString("phone", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PM.
        /// </summary>
        public static string pm {
            get {
                return ResourceManager.GetString("pm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to pound.
        /// </summary>
        public static string pound {
            get {
                return ResourceManager.GetString("pound", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Previous.
        /// </summary>
        public static string Previous {
            get {
                return ResourceManager.GetString("Previous", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price.
        /// </summary>
        public static string Price {
            get {
                return ResourceManager.GetString("Price", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Time.
        /// </summary>
        public static string PriceDate {
            get {
                return ResourceManager.GetString("PriceDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceFavTitle.
        /// </summary>
        public static string PriceFavTitle {
            get {
                return ResourceManager.GetString("PriceFavTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PriceList.
        /// </summary>
        public static string PriceList {
            get {
                return ResourceManager.GetString("PriceList", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prices Offers.
        /// </summary>
        public static string PricesOffers {
            get {
                return ResourceManager.GetString("PricesOffers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price Viewer.
        /// </summary>
        public static string PriceViewer {
            get {
                return ResourceManager.GetString("PriceViewer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Print.
        /// </summary>
        public static string Print {
            get {
                return ResourceManager.GetString("Print", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Printing Date.
        /// </summary>
        public static string PrintingDate {
            get {
                return ResourceManager.GetString("PrintingDate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to privacy Policy.
        /// </summary>
        public static string privacyPolicy {
            get {
                return ResourceManager.GetString("privacyPolicy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procedures.
        /// </summary>
        public static string Procedures {
            get {
                return ResourceManager.GetString("Procedures", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        public static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile Info.
        /// </summary>
        public static string ProfileInfo {
            get {
                return ResourceManager.GetString("ProfileInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search by question or question group.
        /// </summary>
        public static string QuesrtionSearch {
            get {
                return ResourceManager.GetString("QuesrtionSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to question.
        /// </summary>
        public static string Question {
            get {
                return ResourceManager.GetString("Question", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Group.
        /// </summary>
        public static string QuestionGroup {
            get {
                return ResourceManager.GetString("QuestionGroup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Group Description.
        /// </summary>
        public static string QuestionGroupDesc {
            get {
                return ResourceManager.GetString("QuestionGroupDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Order.
        /// </summary>
        public static string QuestionOrder {
            get {
                return ResourceManager.GetString("QuestionOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Questions No Answer.
        /// </summary>
        public static string QuestionsNoAnswer {
            get {
                return ResourceManager.GetString("QuestionsNoAnswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Frequently Asked Questions Group.
        /// </summary>
        public static string QuestionsTitle {
            get {
                return ResourceManager.GetString("QuestionsTitle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Question Type.
        /// </summary>
        public static string QuestionType {
            get {
                return ResourceManager.GetString("QuestionType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read More.
        /// </summary>
        public static string ReadMore {
            get {
                return ResourceManager.GetString("ReadMore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReEmail.
        /// </summary>
        public static string ReEmail {
            get {
                return ResourceManager.GetString("ReEmail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Refresh.
        /// </summary>
        public static string RefreshCaptcha {
            get {
                return ResourceManager.GetString("RefreshCaptcha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReGetPassword.
        /// </summary>
        public static string ReGetPassword {
            get {
                return ResourceManager.GetString("ReGetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region.
        /// </summary>
        public static string Region {
            get {
                return ResourceManager.GetString("Region", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register.
        /// </summary>
        public static string Register {
            get {
                return ResourceManager.GetString("Register", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register in website news feature.
        /// </summary>
        public static string RegisterInNews {
            get {
                return ResourceManager.GetString("RegisterInNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new trader.
        /// </summary>
        public static string RegisterNewTrader {
            get {
                return ResourceManager.GetString("RegisterNewTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register new user.
        /// </summary>
        public static string RegisterNewUser {
            get {
                return ResourceManager.GetString("RegisterNewUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Register now.
        /// </summary>
        public static string RegisterNow {
            get {
                return ResourceManager.GetString("RegisterNow", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Related News.
        /// </summary>
        public static string RelatedNews {
            get {
                return ResourceManager.GetString("RelatedNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reload Advertised Price.
        /// </summary>
        public static string ReloadAdvertisedPrice {
            get {
                return ResourceManager.GetString("ReloadAdvertisedPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to replied.
        /// </summary>
        public static string replied {
            get {
                return ResourceManager.GetString("replied", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Report Type.
        /// </summary>
        public static string ReportType {
            get {
                return ResourceManager.GetString("ReportType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Resend.
        /// </summary>
        public static string Resend {
            get {
                return ResourceManager.GetString("Resend", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to If you didn&apos;t receive the mail send again.
        /// </summary>
        public static string ResendMessage {
            get {
                return ResourceManager.GetString("ResendMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reset Password.
        /// </summary>
        public static string ResetPassword {
            get {
                return ResourceManager.GetString("ResetPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save.
        /// </summary>
        public static string Save {
            get {
                return ResourceManager.GetString("Save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Scatter Line.
        /// </summary>
        public static string ScatterLine {
            get {
                return ResourceManager.GetString("ScatterLine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search.
        /// </summary>
        public static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search Goldsmiths.
        /// </summary>
        public static string SearchGoldsmiths {
            get {
                return ResourceManager.GetString("SearchGoldsmiths", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to search in Sagha.
        /// </summary>
        public static string SearchInSagha {
            get {
                return ResourceManager.GetString("SearchInSagha", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Search News.
        /// </summary>
        public static string SearchNews {
            get {
                return ResourceManager.GetString("SearchNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SearchResultCount.
        /// </summary>
        public static string SearchResultCount {
            get {
                return ResourceManager.GetString("SearchResultCount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to select.
        /// </summary>
        public static string select {
            get {
                return ResourceManager.GetString("select", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell.
        /// </summary>
        public static string Sell {
            get {
                return ResourceManager.GetString("Sell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to sellMin.
        /// </summary>
        public static string sellMin {
            get {
                return ResourceManager.GetString("sellMin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sell Price.
        /// </summary>
        public static string SellPrice {
            get {
                return ResourceManager.GetString("SellPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send.
        /// </summary>
        public static string Send {
            get {
                return ResourceManager.GetString("Send", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Reply.
        /// </summary>
        public static string SendReply {
            get {
                return ResourceManager.GetString("SendReply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Send Subscribe.
        /// </summary>
        public static string sendSubscribe {
            get {
                return ResourceManager.GetString("sendSubscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show.
        /// </summary>
        public static string show {
            get {
                return ResourceManager.GetString("show", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Favorite Price List.
        /// </summary>
        public static string ShowFavLstLink {
            get {
                return ResourceManager.GetString("ShowFavLstLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowFavPrices.
        /// </summary>
        public static string ShowFavPrices {
            get {
                return ResourceManager.GetString("ShowFavPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to show type.
        /// </summary>
        public static string showtype {
            get {
                return ResourceManager.GetString("showtype", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ShowUsers.
        /// </summary>
        public static string ShowUsers {
            get {
                return ResourceManager.GetString("ShowUsers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Since.
        /// </summary>
        public static string Since {
            get {
                return ResourceManager.GetString("Since", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to StoreName.
        /// </summary>
        public static string StoreName {
            get {
                return ResourceManager.GetString("StoreName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader Order.
        /// </summary>
        public static string STraderOrder {
            get {
                return ResourceManager.GetString("STraderOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add super trader.
        /// </summary>
        public static string STraderProfileCreate {
            get {
                return ResourceManager.GetString("STraderProfileCreate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update super trader.
        /// </summary>
        public static string STUpdate {
            get {
                return ResourceManager.GetString("STUpdate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subject.
        /// </summary>
        public static string Subject {
            get {
                return ResourceManager.GetString("Subject", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Submit.
        /// </summary>
        public static string Submit {
            get {
                return ResourceManager.GetString("Submit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string Subscribe {
            get {
                return ResourceManager.GetString("Subscribe", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Subscribe.
        /// </summary>
        public static string subscribebtn {
            get {
                return ResourceManager.GetString("subscribebtn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Your news subscribtion has been cancelled.
        /// </summary>
        public static string SubscribtionCancelled {
            get {
                return ResourceManager.GetString("SubscribtionCancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Super Trader.
        /// </summary>
        public static string SuperTrader {
            get {
                return ResourceManager.GetString("SuperTrader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SuperTraderProfile.
        /// </summary>
        public static string SuperTraderProfile {
            get {
                return ResourceManager.GetString("SuperTraderProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to to.
        /// </summary>
        public static string to {
            get {
                return ResourceManager.GetString("to", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trade data.
        /// </summary>
        public static string Tradedata {
            get {
                return ResourceManager.GetString("Tradedata", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Add Price.
        /// </summary>
        public static string TradePrices {
            get {
                return ResourceManager.GetString("TradePrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader.
        /// </summary>
        public static string Trader {
            get {
                return ResourceManager.GetString("Trader", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traderChart.
        /// </summary>
        public static string traderChart {
            get {
                return ResourceManager.GetString("traderChart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to trader.
        /// </summary>
        public static string traderlabel {
            get {
                return ResourceManager.GetString("traderlabel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader Name.
        /// </summary>
        public static string TraderName {
            get {
                return ResourceManager.GetString("TraderName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Traders.
        /// </summary>
        public static string TraderOnly {
            get {
                return ResourceManager.GetString("TraderOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader price history.
        /// </summary>
        public static string TraderPriceHistory {
            get {
                return ResourceManager.GetString("TraderPriceHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to traderpriceslist.
        /// </summary>
        public static string traderpriceslist {
            get {
                return ResourceManager.GetString("traderpriceslist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader Register.
        /// </summary>
        public static string TraderRegister {
            get {
                return ResourceManager.GetString("TraderRegister", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traders Basket.
        /// </summary>
        public static string TradersBasket {
            get {
                return ResourceManager.GetString("TradersBasket", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traders Comparison.
        /// </summary>
        public static string TradersComparison {
            get {
                return ResourceManager.GetString("TradersComparison", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traders Number {0}.
        /// </summary>
        public static string TradersNumber {
            get {
                return ResourceManager.GetString("TradersNumber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Traders Number 0.
        /// </summary>
        public static string TradersNumber1 {
            get {
                return ResourceManager.GetString("TradersNumber1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trader.
        /// </summary>
        public static string TraderText {
            get {
                return ResourceManager.GetString("TraderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribtion.
        /// </summary>
        public static string unsubscribtion {
            get {
                return ResourceManager.GetString("unsubscribtion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unsubscribtion Failed.
        /// </summary>
        public static string unsubscribtionFailed {
            get {
                return ResourceManager.GetString("unsubscribtionFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error has occurred during the unsubscribe process in the News feature, please make sure of the link.
        /// </summary>
        public static string unsubscribtionFailedMsg {
            get {
                return ResourceManager.GetString("unsubscribtionFailedMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update.
        /// </summary>
        public static string Update {
            get {
                return ResourceManager.GetString("Update", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Price.
        /// </summary>
        public static string updatePrice {
            get {
                return ResourceManager.GetString("updatePrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Prices.
        /// </summary>
        public static string UpdatePrices {
            get {
                return ResourceManager.GetString("UpdatePrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Upload.
        /// </summary>
        public static string Upload {
            get {
                return ResourceManager.GetString("Upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Usage Terms.
        /// </summary>
        public static string UsageTerms {
            get {
                return ResourceManager.GetString("UsageTerms", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Information.
        /// </summary>
        public static string UserInfo {
            get {
                return ResourceManager.GetString("UserInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name.
        /// </summary>
        public static string UserName {
            get {
                return ResourceManager.GetString("UserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User question.
        /// </summary>
        public static string userquestion {
            get {
                return ResourceManager.GetString("userquestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Questions.
        /// </summary>
        public static string userquestioncheck {
            get {
                return ResourceManager.GetString("userquestioncheck", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users.
        /// </summary>
        public static string Users {
            get {
                return ResourceManager.GetString("Users", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Added Users .
        /// </summary>
        public static string UsersNo {
            get {
                return ResourceManager.GetString("UsersNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Users Number.
        /// </summary>
        public static string UsersNoTable {
            get {
                return ResourceManager.GetString("UsersNoTable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User.
        /// </summary>
        public static string UserText {
            get {
                return ResourceManager.GetString("UserText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Type.
        /// </summary>
        public static string UserType {
            get {
                return ResourceManager.GetString("UserType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Video Link.
        /// </summary>
        public static string VideoLink {
            get {
                return ResourceManager.GetString("VideoLink", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to View Report.
        /// </summary>
        public static string ViewReport {
            get {
                return ResourceManager.GetString("ViewReport", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Views number.
        /// </summary>
        public static string ViewsNo {
            get {
                return ResourceManager.GetString("ViewsNo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Week.
        /// </summary>
        public static string Week {
            get {
                return ResourceManager.GetString("Week", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Year/Month.
        /// </summary>
        public static string YearMonth {
            get {
                return ResourceManager.GetString("YearMonth", resourceCulture);
            }
        }
    }
}
