//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18444
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class Messages {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Messages() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Resources.Messages", typeof(Messages).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateNews.
        /// </summary>
        public static string ActivateNews {
            get {
                return ResourceManager.GetString("ActivateNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ActivateQuestion.
        /// </summary>
        public static string ActivateQuestion {
            get {
                return ResourceManager.GetString("ActivateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you will be activate the user on the system?.
        /// </summary>
        public static string ActivateUsr {
            get {
                return ResourceManager.GetString("ActivateUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have to assign traders to your fav. list first..continue?.
        /// </summary>
        public static string AssingToFavRequired {
            get {
                return ResourceManager.GetString("AssingToFavRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again ,the data already defined.
        /// </summary>
        public static string BasketNameDuplicate {
            get {
                return ResourceManager.GetString("BasketNameDuplicate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Two - character minimum.
        /// </summary>
        public static string BasketNameLengthVal {
            get {
                return ResourceManager.GetString("BasketNameLengthVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Name can&apos;t allow numbers.
        /// </summary>
        public static string BasketNameNoNum {
            get {
                return ResourceManager.GetString("BasketNameNoNum", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value you can&apos;t leave this empty.
        /// </summary>
        public static string BasketNameVal {
            get {
                return ResourceManager.GetString("BasketNameVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please Enter Answer And Select Group.
        /// </summary>
        public static string Canotsavequestion {
            get {
                return ResourceManager.GetString("Canotsavequestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verification code is not right.please try again.
        /// </summary>
        public static string CaptchaError {
            get {
                return ResourceManager.GetString("CaptchaError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You should add main category first.
        /// </summary>
        public static string CategoryErrorMsg {
            get {
                return ResourceManager.GetString("CategoryErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only characters are allowed.
        /// </summary>
        public static string CharsOnly {
            get {
                return ResourceManager.GetString("CharsOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose city.
        /// </summary>
        public static string CityVal {
            get {
                return ResourceManager.GetString("CityVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photo shouldn&apos;t be exceed 4 MB.
        /// </summary>
        public static string CompanyLogoLength {
            get {
                return ResourceManager.GetString("CompanyLogoLength", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to company Logo should be of type png or jpg or jpeg or bmp or gif or tiff.
        /// </summary>
        public static string CompanyLogoType {
            get {
                return ResourceManager.GetString("CompanyLogoType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to this is repeated question activate before?.
        /// </summary>
        public static string ConfirmActive {
            get {
                return ResourceManager.GetString("ConfirmActive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thank you for confirming your email. Please.
        /// </summary>
        public static string ConfirmationMessage {
            get {
                return ResourceManager.GetString("ConfirmationMessage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail confirmation don&apos;t match the E-mail.
        /// </summary>
        public static string ConfirmMailVal {
            get {
                return ResourceManager.GetString("ConfirmMailVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to These passwords don&apos;t match. Please  try again?.
        /// </summary>
        public static string ConfirmPassword {
            get {
                return ResourceManager.GetString("ConfirmPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeAtivate Question.
        /// </summary>
        public static string DeAtivateQuestion {
            get {
                return ResourceManager.GetString("DeAtivateQuestion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to DeAtivateUNews.
        /// </summary>
        public static string DeAtivateUNews {
            get {
                return ResourceManager.GetString("DeAtivateUNews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you will be deactivate the user on the system?.
        /// </summary>
        public static string DeAtivateUsr {
            get {
                return ResourceManager.GetString("DeAtivateUsr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to put only two decimal points.
        /// </summary>
        public static string decimalPointValidation {
            get {
                return ResourceManager.GetString("decimalPointValidation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Deleted successfully.
        /// </summary>
        public static string Deleted {
            get {
                return ResourceManager.GetString("Deleted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Delete Faild.
        /// </summary>
        public static string DeleteFailed {
            get {
                return ResourceManager.GetString("DeleteFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant delete this group as it has assigned questions..
        /// </summary>
        public static string DeleteQuestionGroupVal {
            get {
                return ResourceManager.GetString("DeleteQuestionGroupVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Email exists before.
        /// </summary>
        public static string EmailExists {
            get {
                return ResourceManager.GetString("EmailExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid Email Format.
        /// </summary>
        public static string EmailFormat {
            get {
                return ResourceManager.GetString("EmailFormat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter e-mail.
        /// </summary>
        public static string EmailRequired {
            get {
                return ResourceManager.GetString("EmailRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please use only letters (a-z), numbers and full stops..
        /// </summary>
        public static string EnglishCharactersandNumbersOnly {
            get {
                return ResourceManager.GetString("EnglishCharactersandNumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter answer and select group.
        /// </summary>
        public static string EnterGroupandanswer {
            get {
                return ResourceManager.GetString("EnterGroupandanswer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Thanks for your feedback .
        /// </summary>
        public static string FeedbackAutoMail {
            get {
                return ResourceManager.GetString("FeedbackAutoMail", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Can not update the feed now.
        /// </summary>
        public static string FeedError {
            get {
                return ResourceManager.GetString("FeedError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to An error occurred while processing your request..
        /// </summary>
        public static string GeneralError {
            get {
                return ResourceManager.GetString("GeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose governorate.
        /// </summary>
        public static string GovVal {
            get {
                return ResourceManager.GetString("GovVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid old password.
        /// </summary>
        public static string InvalidOldPassword {
            get {
                return ResourceManager.GetString("InvalidOldPassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Invalid username or password.
        /// </summary>
        public static string InvalidUserName {
            get {
                return ResourceManager.GetString("InvalidUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latest news number can not exceed total numer of news.
        /// </summary>
        public static string LatestNewsLimit {
            get {
                return ResourceManager.GetString("LatestNewsLimit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Letters And Numbers Only.
        /// </summary>
        public static string LettersAndNumbersOnly {
            get {
                return ResourceManager.GetString("LettersAndNumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Only Letters.
        /// </summary>
        public static string LettersOnly {
            get {
                return ResourceManager.GetString("LettersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail format not valid.
        /// </summary>
        public static string MailExpErr {
            get {
                return ResourceManager.GetString("MailExpErr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 50 letters.
        /// </summary>
        public static string maxFifty {
            get {
                return ResourceManager.GetString("maxFifty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maximum 200 letters.
        /// </summary>
        public static string MaxTwoHundred {
            get {
                return ResourceManager.GetString("MaxTwoHundred", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Six characters  minimum.
        /// </summary>
        public static string MinLengthSix {
            get {
                return ResourceManager.GetString("MinLengthSix", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Minimum three charaters.
        /// </summary>
        public static string MinLengthThree {
            get {
                return ResourceManager.GetString("MinLengthThree", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to MinLengthTwenty.
        /// </summary>
        public static string MinLengthTwenty {
            get {
                return ResourceManager.GetString("MinLengthTwenty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to minimum 2 letters.
        /// </summary>
        public static string Mintwo {
            get {
                return ResourceManager.GetString("Mintwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 numbers minimum.
        /// </summary>
        public static string MobileLengthVal {
            get {
                return ResourceManager.GetString("MobileLengthVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter mobile number.
        /// </summary>
        public static string mobileReq {
            get {
                return ResourceManager.GetString("mobileReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check the mobile number.
        /// </summary>
        public static string MobileVal {
            get {
                return ResourceManager.GetString("MobileVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Do you want to continue?.
        /// </summary>
        public static string MsgContinue {
            get {
                return ResourceManager.GetString("MsgContinue", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Value can&apos;t be negative.
        /// </summary>
        public static string negativeVal {
            get {
                return ResourceManager.GetString("negativeVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceed the max no of categories.
        /// </summary>
        public static string NewsCategoryMaxVal {
            get {
                return ResourceManager.GetString("NewsCategoryMaxVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to You have exceed the max no of main categories..
        /// </summary>
        public static string NewsMainCategoryMaxVal {
            get {
                return ResourceManager.GetString("NewsMainCategoryMaxVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number can not exceed total numer of news.
        /// </summary>
        public static string NewsOrder {
            get {
                return ResourceManager.GetString("NewsOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose a picture.
        /// </summary>
        public static string NewsPicRequired {
            get {
                return ResourceManager.GetString("NewsPicRequired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Another token was generated.You Can&apos;t use this one now.
        /// </summary>
        public static string NewTokenGenerated {
            get {
                return ResourceManager.GetString("NewTokenGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to noansertoreply.
        /// </summary>
        public static string noansertoreply {
            get {
                return ResourceManager.GetString("noansertoreply", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No results to display.
        /// </summary>
        public static string NoData {
            get {
                return ResourceManager.GetString("NoData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not allowed to edit profile.
        /// </summary>
        public static string NoPermissionToEditProfile {
            get {
                return ResourceManager.GetString("NoPermissionToEditProfile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the buying and selling price for beginning of the day.
        /// </summary>
        public static string NoPriceBefore {
            get {
                return ResourceManager.GetString("NoPriceBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No Selected.
        /// </summary>
        public static string NoSelected {
            get {
                return ResourceManager.GetString("NoSelected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This user is not active, please contact with the site administrator.
        /// </summary>
        public static string NotActiveUser {
            get {
                return ResourceManager.GetString("NotActiveUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the buy price is less than the buy price for traders outside the basket,Are you sure?.
        /// </summary>
        public static string NotBetterBuy {
            get {
                return ResourceManager.GetString("NotBetterBuy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that these prices are equal to prices for traders outside the basket,Are you sure?.
        /// </summary>
        public static string NotBetterPrices {
            get {
                return ResourceManager.GetString("NotBetterPrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please note that the sell price is greater than the sell price for traders outside the basket,Are you sure?.
        /// </summary>
        public static string NotBetterSell {
            get {
                return ResourceManager.GetString("NotBetterSell", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value you can&apos;t leave this empty..
        /// </summary>
        public static string NotEmpty {
            get {
                return ResourceManager.GetString("NotEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter the buying or selling price.
        /// </summary>
        public static string nullablePrices {
            get {
                return ResourceManager.GetString("nullablePrices", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter numbers only.
        /// </summary>
        public static string NumbersOnly {
            get {
                return ResourceManager.GetString("NumbersOnly", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Desc.
        /// </summary>
        public static string OperationDesc {
            get {
                return ResourceManager.GetString("OperationDesc", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Failed.
        /// </summary>
        public static string OperationFailed {
            get {
                return ResourceManager.GetString("OperationFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main Category.
        /// </summary>
        public static string OperationMainCategory {
            get {
                return ResourceManager.GetString("OperationMainCategory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Operation Name.
        /// </summary>
        public static string OperationName {
            get {
                return ResourceManager.GetString("OperationName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number can not exceed total numer of categories.
        /// </summary>
        public static string OrderCategoryErrorMsg {
            get {
                return ResourceManager.GetString("OrderCategoryErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order number can not exceed total numer of main categories.
        /// </summary>
        public static string OrderErrorMsg {
            get {
                return ResourceManager.GetString("OrderErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Order exists before.
        /// </summary>
        public static string OrderExists {
            get {
                return ResourceManager.GetString("OrderExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to This order exsists.
        /// </summary>
        public static string OrderNoErrorMsg {
            get {
                return ResourceManager.GetString("OrderNoErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter trader order.
        /// </summary>
        public static string orderReq {
            get {
                return ResourceManager.GetString("orderReq", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password Changed Before.
        /// </summary>
        public static string PasswordChangedBefore {
            get {
                return ResourceManager.GetString("PasswordChangedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter old password.
        /// </summary>
        public static string PasswordErrorMsg {
            get {
                return ResourceManager.GetString("PasswordErrorMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please complete password information.
        /// </summary>
        public static string PasswordGeneralError {
            get {
                return ResourceManager.GetString("PasswordGeneralError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to passwordSet.
        /// </summary>
        public static string passwordSet {
            get {
                return ResourceManager.GetString("passwordSet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter your password.
        /// </summary>
        public static string PasswordValidationMsg {
            get {
                return ResourceManager.GetString("PasswordValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 11 numbers minimum.
        /// </summary>
        public static string PhoneLengthVal {
            get {
                return ResourceManager.GetString("PhoneLengthVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please check phone number.
        /// </summary>
        public static string phoneVal {
            get {
                return ResourceManager.GetString("phoneVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Price value must be less than one million.
        /// </summary>
        public static string PriceRangeVal {
            get {
                return ResourceManager.GetString("PriceRangeVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value,can&apos;t leave this empty..
        /// </summary>
        public static string QuestionGroupVal {
            get {
                return ResourceManager.GetString("QuestionGroupVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to regenerate password?.
        /// </summary>
        public static string regeneratePassword {
            get {
                return ResourceManager.GetString("regeneratePassword", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please choose region.
        /// </summary>
        public static string RegionVal {
            get {
                return ResourceManager.GetString("RegionVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please re-login.
        /// </summary>
        public static string Relogin {
            get {
                return ResourceManager.GetString("Relogin", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to please enter confirm password.
        /// </summary>
        public static string RePasswordValidationMsg {
            get {
                return ResourceManager.GetString("RePasswordValidationMsg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ReplayQuestionagain.
        /// </summary>
        public static string ReplayQuestionagain {
            get {
                return ResourceManager.GetString("ReplayQuestionagain", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter value you can&apos;t leave this empty..
        /// </summary>
        public static string Required {
            get {
                return ResourceManager.GetString("Required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Cant not load permission roles !.
        /// </summary>
        public static string RolePermissionError {
            get {
                return ResourceManager.GetString("RolePermissionError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Password has been used before.
        /// </summary>
        public static string SamePasswordError {
            get {
                return ResourceManager.GetString("SamePasswordError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Saved successfully.
        /// </summary>
        public static string Saved {
            get {
                return ResourceManager.GetString("Saved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Save failed.
        /// </summary>
        public static string SaveFailed {
            get {
                return ResourceManager.GetString("SaveFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SendReplyConfirm.
        /// </summary>
        public static string SendReplyConfirm {
            get {
                return ResourceManager.GetString("SendReplyConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sent Successfully.
        /// </summary>
        public static string sent {
            get {
                return ResourceManager.GetString("sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to set As Main User ?.
        /// </summary>
        public static string SetAsMainUser {
            get {
                return ResourceManager.GetString("SetAsMainUser", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to fwef@tjurt.gfdj.
        /// </summary>
        public static string String {
            get {
                return ResourceManager.GetString("String", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to subscribe success.
        /// </summary>
        public static string subscribesuccess {
            get {
                return ResourceManager.GetString("subscribesuccess", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to user is super trader.
        /// </summary>
        public static string SuperTraderType {
            get {
                return ResourceManager.GetString("SuperTraderType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Are you sure you want to delete ?.
        /// </summary>
        public static string SureDelete {
            get {
                return ResourceManager.GetString("SureDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Token Expired.
        /// </summary>
        public static string TokenExpired {
            get {
                return ResourceManager.GetString("TokenExpired", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again, Trader mobile no. exists before.
        /// </summary>
        public static string TraderMobileExists {
            get {
                return ResourceManager.GetString("TraderMobileExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again, Trader name exists before.
        /// </summary>
        public static string TraderNameExists {
            get {
                return ResourceManager.GetString("TraderNameExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please enter trader name.
        /// </summary>
        public static string TraderNameVal {
            get {
                return ResourceManager.GetString("TraderNameVal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again, Trader phone no. exists before.
        /// </summary>
        public static string TraderPhoneExists {
            get {
                return ResourceManager.GetString("TraderPhoneExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please try again, Trader shop exists before.
        /// </summary>
        public static string TraderShopExists {
            get {
                return ResourceManager.GetString("TraderShopExists", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to delete record , related data exist.
        /// </summary>
        public static string UnableToDelete {
            get {
                return ResourceManager.GetString("UnableToDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Updated successfully.
        /// </summary>
        public static string Updated {
            get {
                return ResourceManager.GetString("Updated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Update Failed.
        /// </summary>
        public static string UpdateFailed {
            get {
                return ResourceManager.GetString("UpdateFailed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User inactive.
        /// </summary>
        public static string Userinactive {
            get {
                return ResourceManager.GetString("Userinactive", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is incorrect.
        /// </summary>
        public static string UserInCorrect {
            get {
                return ResourceManager.GetString("UserInCorrect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to UserName Repeated.
        /// </summary>
        public static string UserNameRepeated {
            get {
                return ResourceManager.GetString("UserNameRepeated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Not Authorized.
        /// </summary>
        public static string UserNotAuthorized {
            get {
                return ResourceManager.GetString("UserNotAuthorized", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to User Name is not exsist.
        /// </summary>
        public static string userNotExsist {
            get {
                return ResourceManager.GetString("userNotExsist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Verified Before.
        /// </summary>
        public static string VerifiedBefore {
            get {
                return ResourceManager.GetString("VerifiedBefore", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify your account first.
        /// </summary>
        public static string VerifyAccount {
            get {
                return ResourceManager.GetString("VerifyAccount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Please verify user name.
        /// </summary>
        public static string verifyUserName {
            get {
                return ResourceManager.GetString("verifyUserName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zero value not allowed here.
        /// </summary>
        public static string ZeroPrice {
            get {
                return ResourceManager.GetString("ZeroPrice", resourceCulture);
            }
        }
    }
}
